In [ ]:
import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import SGDClassifier
from sklearn import metrics


In [55]:
index_df = pd.read_csv('Chinese_MINST_Dataset/chinese_mnist.csv')

In [56]:
def create_file_name(x):
    file_name = f"input_{x.iloc[0]}_{x.iloc[1]}_{x.iloc[2]}.jpg"
    return file_name

index_df["file"] = index_df.apply(create_file_name, axis=1)

index_df.head()

suite_id  sample_id  code  value character               file
0         1          1    10      9         九   input_1_1_10.jpg
1         1         10    10      9         九  input_1_10_10.jpg
2         1          2    10      9         九   input_1_2_10.jpg
3         1          3    10      9         九   input_1_3_10.jpg
4         1          4    10      9         九   input_1_4_10.jpg

In [57]:
images = []
labels = []

In [58]:
img_root = 'Chinese_MINST_Dataset/data/data/'

In [59]:
for index, row in index_df. iterrows():
    image_path = img_root + row['file']
    image = cv2. imread (image_path, 0)
    images.append (image)
    label = row['code'] - 1
    labels.append (label)

In [ ]:
len(images)

15000

In [61]:
images[0].shape

(64, 64)

In [ ]:
plt.imshow(images[0], 'gray')

In [ ]:
labels[0]

9

In [65]:
images = np.array(images)
labels = np.array(labels)

In [ ]:
train_images, test_images, train_labels, test_labels = train_test_split(
    images, 
    labels, 
    test_size=0.2, 
    random_state=42, 
    stratify=labels
)

fig, axes = plt.subplots(10, 10, figsize=(8, 8), 
                         subplot_kw={'xticks': [], 'yticks': []},
                         gridspec_kw={'hspace': 0.1, 'wspace': 0.1})

for i, ax in enumerate(axes.flat):
    ax.imshow(train_images[i], cmap='binary', interpolation='nearest')
    ax.text(0.05, 0.05, str(train_labels[i]), transform=ax.transAxes, color='green')


In [67]:
print(f"Total images loaded: {len(images)}")
print(f"Train images shape: {train_images.shape}")
print(f"Test images shape: {test_images.shape}")
print(f"Train labels shape: {train_labels.shape}")
print(f"Test labels shape: {test_labels.shape}")


Total images loaded: 15000
Train images shape: (12000, 64, 64)
Test images shape: (3000, 64, 64)
Train labels shape: (12000,)
Test labels shape: (3000,)


First  
train_size = 5000
     test_size =1000

In [68]:
train_size = 5000
test_size = 1000

In [69]:
train_x = train_images[:train_size, :, :]     
train_y = train_labels[:train_size]            
test_x = test_images[:test_size, :, :]         
test_y = test_labels[:test_size]      

In [70]:
train_x.shape

(5000, 64, 64)

In [71]:
test_images.shape

(3000, 64, 64)

In [73]:
print(train_x.shape)
print(test_x.shape)

(5000, 64, 64)
(1000, 64, 64)


In [74]:
x_train = train_x[:5000].reshape(5000, -1)
x_test = test_x.reshape(1000, -1)  

KNN

In [ ]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(x_train, train_y)
predict_y = knn_clf.predict(x_test)

In [76]:
from sklearn import metrics

In [77]:
metrics.precision_score(test_y, predict_y, average='macro')

0.5457051045672068

In [78]:
metrics.precision_score(test_y, predict_y, average='micro')

0.333

In [79]:
metrics.confusion_matrix(test_y, predict_y)

array([[40,  8,  1,  2,  2,  3,  4,  1,  0,  2,  1,  0,  1,  5,  0],
       [ 0, 51,  4,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 33, 28,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 47, 15, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 32,  7,  3, 13,  1,  1,  2,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 19, 24,  7,  0,  7,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0, 49,  1,  0,  0,  0, 11,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 1, 29,  3,  2,  0,  0,  3, 14,  0,  0,  7,  0,  4,  0,  0],
       [ 0, 13,  0,  0,  0,  1,  2,  0, 47,  0,  0,  0,  0,  0,  0],
       [ 0, 27,  3,  5,  1,  0,  8,  6,  0, 15,  2,  0,  0,  3,  3],
       [ 0, 34,  0,  0,  0,  0,  1,  0,  0,  0, 31,  0,  2,  0,  0],
       [ 1, 21,  4,  9,  9,  4,  5,  3,  1,  0,  5, 10,  1,  4,  0],
       [ 0, 28,  2,  2,  0,  0,  3,  0,  0,  0, 12,  0, 18,  0,  0],
       [ 1, 31,  3,  2,  4,  0,  6,  0,  1,  1,  2,  2,  0, 20,  0],
       [ 1, 33,  4,  3,  1,  2,  7

In [80]:
metrics.f1_score(test_y, predict_y,average='macro')

0.35391554606626685

In [127]:
metrics.accuracy_score(test_y, predict_y)

0.333

In [128]:
metrics.recall_score(test_y, predict_y, average='macro')

0.3397892622349323

In [134]:
metrics.recall_score(test_y, predict_y, average='micro')

0.333

In [129]:
metrics.f1_score(test_y, predict_y, average='micro')

0.333

DT Classifier:

In [81]:
dt_clf = DecisionTreeClassifier (random_state=0)
dt_clf.fit(x_train, train_y)
predict_y_dt = dt_clf.predict (x_test)


In [133]:
metrics.accuracy_score(test_y, predict_y_dt)

0.306

In [82]:
metrics.precision_score(test_y, predict_y_dt, average='macro')

0.2625696497816648

In [83]:
metrics.precision_score(test_y, predict_y_dt, average='micro')

0.263

In [131]:
metrics.recall_score(test_y, predict_y, average='macro')

0.3397892622349323

In [132]:
metrics.recall_score(test_y, predict_y, average='micro')

0.333

In [84]:
metrics.confusion_matrix(test_y, predict_y_dt)

array([[26,  0,  0,  6,  7,  5,  2,  0,  0,  2,  2,  6,  5,  7,  2],
       [ 0, 36,  9,  0,  0,  2,  3,  1,  0,  0,  2,  1,  0,  1,  1],
       [ 0, 12, 14,  6,  2,  4,  2,  5,  5,  3,  2,  1,  4,  2,  3],
       [ 1,  5, 10, 21,  3,  5,  5,  7,  3,  3,  4,  1,  5,  6,  5],
       [ 4,  0,  2,  6, 10,  4,  6,  0,  3,  3,  2,  6,  3,  4,  6],
       [ 3,  1,  2,  7,  0, 11,  2,  9,  3,  4,  0,  4,  3,  9,  1],
       [ 2,  0,  4,  5,  6,  2,  7,  3,  8,  5,  2,  0,  8,  3,  7],
       [ 1,  2,  1,  2,  6,  4,  4, 13,  6,  7,  1,  1,  8,  4,  3],
       [ 1,  3,  3,  4,  0,  1,  1,  6, 31,  2,  2,  1,  5,  1,  2],
       [ 3,  2,  5, 10,  1,  4,  5,  5,  4,  9,  2,  6,  2,  8,  7],
       [ 1,  4,  1,  0,  0,  2,  3,  5,  7,  1, 27,  3, 10,  3,  1],
       [ 3,  1,  3,  5, 10,  7,  8,  4,  4,  5,  2, 13,  5,  4,  3],
       [ 1,  2,  5,  2,  0,  2,  3,  5,  0,  1,  8,  5, 23,  6,  2],
       [ 0,  1,  4,  4,  3,  4,  5,  5,  9,  6,  1,  8,  4, 13,  6],
       [ 5,  1,  3,  8,  7,  3,  6

In [85]:
metrics.f1_score(test_y, predict_y_dt, average='macro')

0.26203192815995385

In [130]:
metrics.f1_score(test_y, predict_y_dt, average='micro')

0.306

SGD classifier:

In [87]:
sgd_clf = SGDClassifier(max_iter=250)
sgd_clf.fit(x_train, train_y)
predict_y_sgd = sgd_clf.predict(x_test)

In [135]:
metrics.accuracy_score(test_y, predict_y_sgd)

0.291

In [136]:
metrics.recall_score(test_y, predict_y_sgd, average='macro')

0.2954444859217064

In [137]:
metrics.recall_score(test_y, predict_y_sgd, average='micro')

0.291

In [88]:
metrics.precision_score(test_y, predict_y_sgd, average='macro')

0.29340468788728025

In [89]:
metrics.precision_score(test_y, predict_y_sgd, average='micro')

0.274

In [90]:
metrics.confusion_matrix(test_y, predict_y_sgd)

array([[34,  0,  0,  0,  2,  0,  1,  3,  1,  5,  1, 14,  3,  5,  1],
       [ 3, 15,  6,  4,  1,  5,  5,  3,  0,  1,  5,  1,  1,  4,  2],
       [ 1,  3, 19,  6,  4,  6,  3,  7,  4,  1,  1,  2,  0,  3,  5],
       [ 2,  1, 11, 19,  3, 13,  5,  1,  0,  7,  0,  8,  8,  4,  2],
       [ 3,  0,  3,  3, 13,  4,  8,  3,  2,  2,  2,  9,  0,  2,  5],
       [ 0,  0,  9,  4,  5, 15,  4,  4,  0,  5,  2,  8,  1,  1,  1],
       [ 3,  0,  2,  3,  7,  0, 16,  4,  4, 11,  1,  4,  2,  4,  1],
       [ 4,  1,  3,  6,  5,  2,  1, 14,  4,  5,  4,  6,  1,  5,  2],
       [ 2,  3,  5,  3,  4,  3,  3,  5, 18,  4,  0,  3,  1,  4,  5],
       [ 4,  1,  1,  6,  1,  7, 11,  6,  2, 12,  5,  8,  2,  5,  2],
       [ 5,  2,  1,  3,  2,  4,  1,  7,  1,  0, 28,  5,  6,  2,  1],
       [ 4,  1,  5,  5,  3,  6,  6,  3,  4,  3,  3, 18,  3, 10,  3],
       [ 7,  0,  2,  2,  0,  6,  4,  4,  2,  1,  9,  6, 14,  5,  3],
       [ 6,  0,  2,  1,  5,  5,  5,  4,  1,  6,  4, 11,  1, 19,  3],
       [ 0,  1,  0,  3, 10,  6,  3

In [91]:
metrics.f1_score(test_y, predict_y_sgd, average='macro')

0.27843489587957765

In [138]:
metrics.f1_score(test_y, predict_y_sgd, average='micro')

0.291

Second train_size = 10000    test_size =1000

In [92]:
train_size = 10000  
test_size = 1000    

In [93]:
train_x = train_images[:train_size, :, :]
train_y = train_labels[:train_size]
test_x = test_images[:test_size, :, :]
test_y = test_labels[:test_size]

In [98]:
print(train_x.shape)
print(test_x.shape)

(10000, 64, 64)
(1000, 64, 64)


In [104]:
x_train = train_x[:100000].reshape(10000, -1)
x_test = test_x.reshape(1000, -1)  #碾平


KNN Classifier: 

In [140]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(x_train, train_y)  
predict_y_knn = knn_clf.predict(x_test) 

In [141]:
metrics.accuracy_score(test_y, predict_y_knn)

0.413

In [ ]:
metrics.recall_score(test_y, predict_y_knn, average='macro')

0.4206540546229808

In [ ]:
metrics.recall_score(test_y, predict_y_knn, average='micro')

0.413

In [106]:
metrics.precision_score(test_y, predict_y_knn, average='macro')

0.5867807924056289

In [107]:
metrics.precision_score(test_y, predict_y_knn, average='micro')

0.413

In [108]:
metrics.confusion_matrix(test_y, predict_y_knn)

array([[48,  4,  0,  3,  0,  1,  4,  1,  1,  0,  2,  2,  0,  4,  0],
       [ 0, 53,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 31, 28,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 35, 19, 29,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1, 19,  9,  3, 21,  1,  3,  0,  0,  0,  0,  2,  0,  0,  0],
       [ 1, 11, 25, 12,  0,  9,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 36,  1,  1,  0,  0, 23,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 0, 25,  6,  0,  0,  1,  4, 16,  0,  0, 10,  0,  1,  0,  0],
       [ 0,  8,  0,  0,  0,  0,  1,  0, 54,  0,  0,  0,  0,  0,  0],
       [ 1, 20,  2,  3,  1,  0, 12,  5,  0, 20,  3,  0,  0,  4,  2],
       [ 0, 21,  0,  0,  0,  0,  2,  1,  0,  0, 39,  0,  5,  0,  0],
       [ 1, 13,  7, 11,  7,  3,  5,  1,  1,  0,  8, 14,  1,  5,  0],
       [ 0, 24,  0,  0,  0,  0,  0,  0,  0,  0, 17,  1, 23,  0,  0],
       [ 4, 30,  4,  1,  3,  3,  3,  0,  0,  1,  2,  2,  0, 20,  0],
       [ 1, 19,  4,  4,  1,  1,  4

In [109]:
metrics.f1_score(test_y, predict_y_knn, average='macro')

0.43111425355213245

In [144]:
metrics.f1_score(test_y, predict_y_knn, average='micro')

0.413

DT Classifier: 

In [115]:
dt_clf = DecisionTreeClassifier(random_state=0)
dt_clf.fit(x_train, train_y)
predict_y_dt = dt_clf.predict(x_test)

In [148]:
metrics.accuracy_score(test_y, predict_y_dt)

0.306

In [ ]:
metrics.recall_score(test_y, predict_y_dt, average='macro')

0.3116204676859478

In [ ]:
metrics.recall_score(test_y, predict_y_dt, average='micro')

0.306

In [116]:
metrics.precision_score(test_y, predict_y_dt, average='macro')

0.3117425303041964

In [ ]:
metrics.precision_score(test_y, predict_y_dt, average='micro')

0.306

In [118]:
metrics.confusion_matrix(test_y, predict_y_dt)

array([[25,  0,  0,  2,  6,  6,  2,  1,  0,  2,  0, 12,  5,  5,  4],
       [ 0, 38,  6,  4,  0,  1,  1,  1,  3,  0,  1,  0,  1,  0,  0],
       [ 0, 10, 25,  9,  0,  3,  4,  5,  2,  0,  2,  0,  1,  4,  0],
       [ 1,  2, 10, 26,  0,  6,  9,  8,  3,  3,  4,  0,  6,  4,  2],
       [ 7,  0,  0,  2, 16,  9,  4,  5,  2,  3,  0,  4,  3,  2,  2],
       [ 2,  2,  3,  6,  5, 10,  3,  3,  3,  9,  0,  7,  2,  4,  0],
       [ 2,  3,  5,  6,  1,  4, 16,  5,  5,  4,  2,  1,  3,  4,  1],
       [ 3,  2,  3,  1,  2,  3,  6, 18,  4,  4,  2,  3,  7,  3,  2],
       [ 0,  4,  1,  3,  1,  3,  4,  4, 27,  3,  6,  0,  2,  2,  3],
       [ 2,  0,  1,  2,  3,  9, 15,  9,  3,  9,  2,  7,  0,  4,  7],
       [ 1,  1,  4,  1,  0,  1,  7,  4,  2,  2, 30,  0, 12,  3,  0],
       [ 3,  0,  1,  1,  7,  9,  5,  6,  2,  8,  2, 13,  6, 10,  4],
       [ 4,  0,  1,  3,  1,  3,  3,  1,  0,  3, 13,  2, 26,  4,  1],
       [ 1,  0,  2,  7,  3,  7,  5,  6,  3,  4,  3,  9,  5, 14,  4],
       [ 5,  0,  4,  5, 12,  3,  1

In [119]:
metrics.f1_score(test_y, predict_y_dt, average='macro')

0.30922970207337674

In [145]:
metrics.f1_score(test_y, predict_y_dt, average='micro')

0.306

SGD

In [120]:
sgd_clf = SGDClassifier(max_iter=250)
sgd_clf.fit(x_train, train_y)  # 使用展平后的训练数据
predict_y_sgd = sgd_clf.predict(x_test)  # 使用展平后的测试数据

In [150]:
metrics.accuracy_score(test_y, predict_y_sgd)

0.291

In [ ]:
metrics.precision_score(test_y, predict_y_sgd, average='macro')

0.3344246977547477

In [ ]:
metrics.precision_score(test_y, predict_y_sgd, average='micro')

0.291

In [121]:
metrics.precision_score(test_y, predict_y_sgd, average='macro')

0.3344246977547477

In [ ]:
metrics.precision_score(test_y, predict_y_sgd, average='micro')

0.291

In [ ]:
metrics.confusion_matrix(test_y, predict_y_sgd)

array([[35,  0,  0,  0,  1,  7,  1,  6,  0,  4,  1,  6,  2,  5,  2],
       [ 0, 18, 17,  3,  3,  4,  2,  0,  0,  2,  2,  0,  0,  2,  3],
       [ 1,  3, 25,  3,  0,  9,  2,  8,  2,  2,  0,  2,  2,  1,  5],
       [ 0,  1, 18, 16,  2, 17,  2,  2,  0,  7,  0,  3,  6,  2,  8],
       [ 5,  1,  5,  0, 15, 11,  3,  3,  0,  4,  1,  3,  2,  2,  4],
       [ 3,  1, 10,  2,  0, 20,  3,  5,  0,  6,  1,  3,  2,  2,  1],
       [ 0,  0,  5,  3,  2,  4, 15,  3,  5, 12,  1,  5,  5,  2,  0],
       [ 2,  1,  6,  2,  2, 10,  1, 22,  3,  5,  1,  1,  2,  2,  3],
       [ 0,  3,  5,  3,  2,  7,  4,  4, 24,  3,  0,  2,  0,  1,  5],
       [ 2,  0,  3,  0,  2, 12,  9,  8,  3, 21,  2,  3,  2,  1,  5],
       [ 3,  0,  3,  0,  5, 11,  1, 11,  1,  5, 11,  3,  7,  5,  2],
       [ 4,  0,  3,  2,  5, 14,  4, 11,  2,  1,  1, 12,  2,  9,  7],
       [ 5,  1,  5,  1,  1,  8,  3,  5,  1,  4,  5,  1, 20,  2,  3],
       [ 9,  0,  1,  0,  2,  7,  4,  6,  0, 10,  2, 10,  5, 14,  3],
       [ 2,  0,  3,  1,  4,  3,  1

In [124]:
metrics.f1_score(test_y, predict_y_sgd, average='macro')

0.29798085191777196

In [149]:
metrics.f1_score(test_y, predict_y_sgd, average='micro')

0.291

The performance of KNN, Decision Tree (DT), and Stochastic Gradient Descent (SGD) classifiers varies with dataset size.

With 5,000 training samples:

KNN tends to underfit due to the limited number of neighbors.
DT may exhibit unstable performance or overfit the data.
SGD struggles to converge reliably.
With 10,000 training samples:

KNN achieves higher accuracy but at the cost of increased computational time.
DT sees accuracy improvements but remains prone to overfitting unless properly pruned.
SGD demonstrates significant gains in both accuracy and stability, highlighting its advantage in handling larger datasets.
Overall, SGD is the preferred choice for large datasets due to its efficiency in training, DT offers interpretability but requires caution against overfitting, and KNN is better suited for smaller, well-balanced datasets.